version: '3.4'
services:
  redis:
    image: redis:5.0-alpine
    ports:
      - 63790:6379
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
    volumes:
      - ./data:/var/lib/postgresql/data:cached
    ports:
      - 54320:5432
  vets-api:
    build:
      context: .
      args:
        sidekiq_license: "${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}"
    image: vets-api:latest
    volumes:
      - .:/srv/vets-api/src:cached
      - "../vets-api-mockdata:/cache"
    ports:
      - 3000:3000
    environment:
      "Settings.database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_development}?pool=4"
      "Settings.test_database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_test}"
      "Settings.redis.app_data.url": "redis://redis:6379"
      "Settings.redis.sidekiq.url": "redis://redis:6379"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
