version: '3.8'
services:
  redis:
    image: redis:5.0-alpine
    ports:
      - 63790:6379
  postgres:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
    image: mdillon/postgis:11-alpine
    ports:
      - 54320:5432
    volumes:
      - ./data:/var/lib/postgresql/data:cached
  web:
    build:
      context: .
      target: development
    environment:
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: "${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}"
      "Settings.database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_development}?pool=4"
      "Settings.test_database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_test}"
      "Settings.redis.app_data.url": "redis://redis:6379"
      "Settings.redis.sidekiq.url": "redis://redis:6379"
    image: vets-api:latest
    ports:
      - 3000:3000
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app:cached
    working_dir: /app
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
volumes:
  bundle_cache:
